steps:
  - name: 'gcr.io/malloy-303216/vscode-builder'
    entrypoint: 'bash'
    args:
      - -c
      - './cloudbuild/deploy/$TRIGGER_NAME.sh'
    timeout: '1800s'
    secretEnv:
      [
        'VSCE_PAT',
        'OVSX_TOKEN',
        'GA_API_SECRET',
        'GA_MEASUREMENT_ID',
        'GHAPI_PAT',
      ]
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1800s'
availableSecrets:
  secretManager:
    - versionName: projects/malloy-303216/secrets/marketplace-prerelease-CI/versions/latest
      env: 'VSCE_PAT'
    - versionName: projects/673673622326/secrets/ovsx-token/versions/latest
      env: OVSX_TOKEN
    - versionName: projects/malloy-303216/secrets/vscode-extension-CI-GA-API-SECRET/versions/latest
      env: 'GA_API_SECRET'
    - versionName: projects/malloy-303216/secrets/vscode-extension-CI-GA-MEASUREMENT-ID/versions/latest
      env: 'GA_MEASUREMENT_ID'
    - versionName: projects/malloy-303216/secrets/vscode-extension-gh-pat/versions/latest
      env: 'GHAPI_PAT'
