steps:
  - name: gcr.io/cloud-builders/git
    args: ['submodule', 'update', '--init', '--recursive']
  - name: 'gcr.io/malloy-303216/vscode-builder'
    entrypoint: 'bash'
    args:
      - '-c'
      - './cloudbuild/build-test/$TRIGGER_NAME.sh'
timeout: '1600s'
